# Generated by Django 3.2.11 on 2023-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinformation',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
