# Generated by Django 3.2.11 on 2023-01-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_jobinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
